### ISSUE TITLE
Automate the training process with "Auto-sklearn"

### ISSUE THREAD

**Issue by kRiShNa-429407** [NISYSLAB/numpy-analyzer#1]
We can automate the training process with Autosklearn, and by autosklearn.leaderboard method give the leaderboard of different models with their score.

**Comment by kRiShNa-429407** [comment]
I want to contribute for GSOC 2024

**Comment by zeydabadi** [comment]
Please first educate yourself on how to apply.

**Comment by kRiShNa-429407** [comment]
I know pandas, NumPy, matplotlib and scikit learn.
Currently working on heart_disease_classification project.
